name: Release Storybook to GitHubPages

on:
  push:
    branches:
      - main

env:
  cache-version: v1

jobs:
  release:
    name: Project Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Navigate to frontend
        run: cd frontend

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.0
      - name: Install Node Dependencies
        run: pnpm install

      - name: Build package
        run: npm run build

      - name: Build storybook
        run: npm run build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/storybook
