name: Release Storybook to GitHubPages

on:
  push:
    branches:
      - main

env:
  cache-version: v1

jobs:
  release:
    name: Project Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: ./frontend

      - name: Build storybook
        run: bun run prisma generate && bun run build-storybook -o ./dist/storybook
        working-directory: ./frontend

      - name: Create dist/frontend directory
        run: mkdir -p ./dist/frontend
        working-directory: ./frontend

      - name: Copy vercel-ignore-build-step.sh to dist/frontend directory
        run: cp ./vercel-ignore-build-step.sh ./dist/frontend
        working-directory: ./frontend

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
